import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="es"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}
        <footer style={{ textAlign: "center", padding: "1rem", fontSize: "0.9rem" }}>
          Desarrollado por{" "}
          <a href="https://github.com/Ian-M-09" target="_blank" rel="noopener noreferrer">
            Ian Miño
          </a>
        </footer>
      </body>
    </html>
  );
}
